//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchaFournisseurs
    {
        public int ID { get; set; }
        public int AchatID { get; set; }
        public int FournisseurID { get; set; }
        public float Price { get; set; }
        public float Remise { get; set; }
        public System.DateTime Dt { get; set; }
        public int State { get; set; }
    
        public virtual Achats Achats { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
    }
}
