//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Fournisseurs = new HashSet<Fournisseurs>();
        }
    
        public int ID { get; set; }
        public string Lbl { get; set; }
    
        public virtual ICollection<Fournisseurs> Fournisseurs { get; set; }
    }
}
