//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fournisseurs
    {
        public Fournisseurs()
        {
            this.AchaFournisseurs = new HashSet<AchaFournisseurs>();
            this.Categories = new HashSet<Categories>();
        }
    
        public int ID { get; set; }
        public string Nom_frn { get; set; }
        public string Adress_frn { get; set; }
        public string Mail_frn { get; set; }
        public string Tel_frn { get; set; }
    
        public virtual ICollection<AchaFournisseurs> AchaFournisseurs { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
